remote_theme: pmarsceill/just-the-docs

title: SGCT
description: Simple Graphics Cluster Toolkit
#logo: "/assets/images/logo.png"

search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
footer_content: "Copyright &copy; 2012-2020. Distributed by an <a href=\"https://github.com/SGCT/SGCT/tree/master/LICENSE.md\">3-clause BSD license.</a>"
color_scheme: "dark"

aux_links:
  "SGCT on GitHub":
    - "//github.com/SGCT/SGCT"

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed